### PR TITLE
Wrong scoreboard color

### PR DESCRIPTION
**Pull request by TheNickSkater**
This just fixes the "?" to be the class color of the last class the player had.

### CODE REVIEW

**Comment by TimGoll** [comment]
wouldn't it be better to reset the color of the class if the class is unknown?

**Comment by TheNickSkater** [comment]
> wouldn't it be better to reset the color of the class if the class is unknown?

This is not for other players.

In preparing only MY "?" is the last color of the class I had, not other players.

**Comment by TimGoll** [comment]
yes, I meant that. Resetting the last color.
But I see, the last color is "cached" in the label and not in some TTTC specific object. Am I right?

**Comment by TheNickSkater** [comment]
> yes, I meant that. Resetting the last color.
> But I see, the last color is "cached" in the label and not in some TTTC specific object. Am I right?

Yes afaik thats how it is. The Label is never reseted back to white.

**Comment by TimGoll** [comment]
Okay, looks good to me, I'll merge it! :)

**Pull request merged**
