### PR TITLE
Added class team sync

### PR DESCRIPTION
**Pull request by TheNickSkater**
This will add the possibility to sync the classes of Teammates.

This is not yet tested! I will do so when I have time. All complaints etc to me please.

### CODE REVIEW

**Comment by TimGoll** [comment]
Please test and report back. LeBroomer said that syncing classes to teammates is not that easy.

**Comment by TheNickSkater** [comment]
> Please test and report back. LeBroomer said that syncing classes to teammates is not that easy.

Did test now and it works pretty good without problems. It just does not (yet) take role/team changes into account.. Even tough IDK if that should even happen (if a Traitor gets sidekick, other traitors shoul still see his class).

**Comment by TheNickSkater** [comment]
@lebroomer Should take a look at this.

Again, I tested it the other day for quite some time and it seemed to work without problems.. We'd just need to discuss if it is necessary or even good to update the classes on Role-/Teamchange and how.

**Comment by TheNickSkater** [comment]
As I have this running on my Server for quite some time now, I can say it works good. Like I already mentioned, only thing we should think about is RoleChange/TeamChange.

**Comment by lebroomer** [comment]
Yes the problem was the complicated and with the current system impossible (as you can see with the sidekick color change) sync, whenever someone switches teams, which is a problem for roles like pirate. And as far I can see the current behavior would reveal the identity of the spy.

**Comment by lebroomer** [comment]
Nvm I just saw the hook for the spy. Then I am fine with the PR as long as the sync change isn't done.

**Pull request merged**
